@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package denimred.simplemuseum.modcompat.cryptmaster;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;
