@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package denimred.simplemuseum;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
