@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package denimred.simplemuseum.modcompat;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;
