@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package denimred.simplemuseum.modcompat;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
